CREATE OR REPLACE TRIGGER T81TCLI_PERSONA
BEFORE INSERT ON TCLI_PERSONA    
 REFERENCING NEW AS NEW OLD AS OLD  
  FOR EACH ROW
DECLARE
horai  number(5);
horaf  number(5);
horaid number(5);
horafd number(5);
BEGIN
  IF :NEW.CLI_FECHAING IS NULL THEN
      :NEW.CLI_FECHAING:=SYSDATE;
  END IF;
END ;
